# Generated by Django 4.2.2 on 2023-06-08 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_trainingdata_trainingday_delete_dayofweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.exercise')),
            ],
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='workouts',
        ),
        migrations.AddField(
            model_name='log',
            name='sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='routine',
            name='days_of_week',
            field=models.ManyToManyField(to='main_app.trainingday'),
        ),
        migrations.AlterField(
            model_name='log',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TrainingData',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.AddField(
            model_name='plannedexercise',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.routine'),
        ),
    ]
